<?php

namespace App\Console\Commands;

use App\Core\ErrorDefinition\ErrorDefinitionDiscovery;
use App\Core\ErrorDefinition\ErrorDefinitionLinter;
use App\Core\ErrorDefinition\ErrorDefinitionReader;
use App\Core\ErrorDefinition\ErrorCode;
use BackedEnum;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use ReflectionClass;

class GenerateErrorCatalogCommand extends Command
{
    protected $signature = 'error-definition:generate
        {--check : Validate that generated artifacts are up-to-date without writing files}';

    protected $description = 'Generate TypeScript error codes and JSON catalog from ErrorDefinition enums';

    public function handle(): int
    {
        $this->info('Scanning ErrorDefinition enums...');

        $discovery = new ErrorDefinitionDiscovery();
        $result = $discovery->discover();

        $linter = new ErrorDefinitionLinter();
        $report = $linter->lint($result->errorEnums, $result->formRequests);

        if ($report->hasErrors()) {
            foreach ($report->errors() as $finding) {
                $this->error("[{$finding->ruleId}] {$finding->source}: {$finding->message}");
            }
            $this->error('❌ Lint failed. Perbaiki error di atas sebelum generate artifact.');
            return 1;
        }

        $reader = app(ErrorDefinitionReader::class);

        $catalog = [];
        $tsConstEntries = [];

        foreach ($result->errorEnums as $className) {
            if (!class_exists($className) && !enum_exists($className)) {
                continue;
            }

            $ref = new ReflectionClass($className);
            if (!$ref->implementsInterface(ErrorCode::class) || !$ref->isEnum()) {
                continue;
            }

            foreach ($className::cases() as $case) {
                /** @var ErrorCode&BackedEnum $case */
                $resolved = $reader->read($case);
                $catalog[] = [
                    'code' => $resolved->code,
                    'message' => $resolved->message,
                    'category' => strtolower($resolved->category->value),
                    'httpStatus' => $resolved->httpStatus,
                    'severity' => strtolower($resolved->severity->value),
                    'retryable' => $resolved->retryable,
                ];

                $tsKey = str_replace('-', '_', $resolved->code);
                $tsConstEntries[] = "  '{$tsKey}': '{$resolved->code}',";
            }
        }

        usort($catalog, fn ($a, $b) => strcmp($a['code'], $b['code']));
        sort($tsConstEntries, SORT_STRING);

        $jsonCatalog = $this->reindentJson(json_encode(
            ['schemaVersion' => 1, 'errors' => $catalog],
            JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        )) . "\n";

        $tsContent = "// This file is generated by Error Definition Framework.\n"
            . "// Do not edit manually.\n\n"
            . "export const ERROR_CODES = {\n"
            . implode("\n", $tsConstEntries) . "\n"
            . "} as const;\n\n"
            . "export type ErrorCode =\n"
            . "  (typeof ERROR_CODES)[keyof typeof ERROR_CODES];\n";

        $jsonPath = storage_path('app/error-definition/error-catalog.json');
        $tsPath = resource_path('js/generated/error-codes.ts');

        if ($this->option('check')) {
            $hasChanges = false;

            if (!file_exists($jsonPath) || file_get_contents($jsonPath) !== $jsonCatalog) {
                $this->error('error-catalog.json is out of date.');
                $hasChanges = true;
            }

            if (!file_exists($tsPath) || file_get_contents($tsPath) !== $tsContent) {
                $this->error('error-codes.ts is out of date.');
                $hasChanges = true;
            }

            if ($hasChanges) {
                $this->error('Run `php artisan error-definition:generate` to update.');
                return 1;
            }

            $this->info('✅ Generated artifacts are up-to-date.');
            return 0;
        }

        File::ensureDirectoryExists(storage_path('app/error-definition'));
        File::put($jsonPath, $jsonCatalog);

        File::ensureDirectoryExists(resource_path('js/generated'));
        File::put($tsPath, $tsContent);

        $this->info('Generated: storage/app/error-definition/error-catalog.json');
        $this->info('Generated: resources/js/generated/error-codes.ts');
        $this->info(sprintf('Total: %d error definition(s) from %d enum(s).', count($catalog), count($result->errorEnums)));

        return 0;
    }

    /**
     * PHP's JSON_PRETTY_PRINT selalu memakai indentasi 4 spasi; kontrak mensyaratkan 2 spasi.
     */
    private function reindentJson(string $json): string
    {
        return preg_replace_callback('/^ +/m', function (array $matches): string {
            return str_repeat(' ', (int) (strlen($matches[0]) / 2));
        }, $json);
    }
}
