<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $partitioningEnabled = (bool) config('activity-log.partitioning_enabled', false);
        $driver = DB::getDriverName();

        if ($partitioningEnabled) {
            if ($driver !== 'oracle') {
                throw new RuntimeException(
                    "Activity log partitioning is enabled, but current database driver [{$driver}] does not support partitioned DDL."
                );
            }

            DB::statement("
                CREATE TABLE tm_activity_log (
                    i_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                    v_subject_type VARCHAR2(100) NOT NULL,
                    v_subject_id VARCHAR2(100) NOT NULL,
                    v_event VARCHAR2(50) NOT NULL,
                    v_causer_id VARCHAR2(100) NOT NULL,
                    v_impersonator_id VARCHAR2(100) NULL,
                    v_request_id VARCHAR2(36) NULL,
                    v_ip_address VARCHAR2(45) NULL,
                    j_properties CLOB CHECK (j_properties IS JSON) NULL,
                    dt_created_at DATE DEFAULT SYSDATE NOT NULL,
                    CONSTRAINT pk_tm_activity_log PRIMARY KEY (i_id)
                )
                PARTITION BY RANGE (dt_created_at)
                INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
                (
                    PARTITION p_initial VALUES LESS THAN (TO_DATE('2026-01-01', 'YYYY-MM-DD'))
                )
            ");

            DB::statement('CREATE INDEX idx_actlog_subj LOCAL ON tm_activity_log (v_subject_type, v_subject_id)');
            DB::statement('CREATE INDEX idx_actlog_causer LOCAL ON tm_activity_log (v_causer_id)');
            DB::statement('CREATE INDEX idx_actlog_impers LOCAL ON tm_activity_log (v_impersonator_id)');
            DB::statement('CREATE INDEX idx_actlog_reqid LOCAL ON tm_activity_log (v_request_id)');

            return;
        }

        Schema::create('tm_activity_log', function (Blueprint $table) {
            $table->id('i_id');
            $table->string('v_subject_type', 100);
            $table->string('v_subject_id', 100);
            $table->string('v_event', 50);
            $table->string('v_causer_id', 100);
            $table->string('v_impersonator_id', 100)->nullable();
            $table->string('v_request_id', 36)->nullable();
            $table->string('v_ip_address', 45)->nullable();
            $table->json('j_properties')->nullable();
            $table->timestamp('dt_created_at')->useCurrent();

            $table->index(['v_subject_type', 'v_subject_id']);
            $table->index('v_causer_id');
            $table->index('v_impersonator_id');
            $table->index('v_request_id');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('tm_activity_log');
    }
};
