<?php

return [
    'disable' => env('CAPTCHA_DISABLE', env('APP_ENV', 'production') !== 'production'),
    'characters' => ['1', '2', '3', '4', '6', '7', '8', '9', '0'],
    'fontsDirectory' => base_path('vendor/mews/captcha/assets/fonts'),
    'bgsDirectory' => base_path('vendor/mews/captcha/assets/backgrounds'),
    'default' => [
        'length' => 6,
        'width' => 345,
        'height' => 65,
        'quality' => 90,
        'math' => false,
        'expire' => 60,
        'encrypt' => false,
    ],
    'flat' => [
        'length' => 5,
        'width' => 150,
        'height' => 30,
        'textLeftPadding' => 10,
        'marginTop' => 5,
        'quality' => 90,
        'lines' => -1,
        'angle' => -15,
        'bgImage' => false,
        'bgColor' => '#f4f4f5',
        'lineColor' => '#e4e4e7',
        'fontColors' => ['#333333', '#444444', '#555555'],
        'contrast' => 0,
        'encrypt' => false,
        // 'length' => 6,
        // 'fontColors' => ['#2c3e50', '#c0392b', '#16a085', '#c0392b', '#8e44ad', '#303f9f', '#f57c00', '#795548'],
        // 'width' => 345,
        // 'height' => 65,
        // 'math' => false,
        // 'quality' => 100,
        // 'lines' => 6,
        // 'bgImage' => true,
        // 'bgColor' => '#28faef',
        // 'contrast' => 0,
    ],
    'mini' => [
        'length' => 3,
        'width' => 60,
        'height' => 32,
    ],
    'inverse' => [
        'length' => 5,
        'width' => 120,
        'height' => 36,
        'quality' => 90,
        'sensitive' => true,
        'angle' => 12,
        'sharpen' => 10,
        'blur' => 2,
        'invert' => false,
        'contrast' => -5,
    ],
    'math' => [
        'length' => 9,
        'width' => 120,
        'height' => 36,
        'quality' => 90,
    ],
];
