<?php

return [
    'keep_lower_case' => [
        'dan',
        'atau',
        'untuk',
        'di',
        'ke',
        'dari',
        'yang',
        'pada',
        'dengan',
    ],

    'keep_upper_case' => [
        'DKI',
        'TLRH',
        'PNS',
        'BUMN',
        'BUMD',
        'PTSP',
        'PMPTSP',
        'SD',
        'SDN',
        'SMP',
        'SMPN',
        'SMA',
        'SMAN',
        'SMK',
        'SMKN',
        'SLTP',
        'MTS',
        'TK',
        'TL',
        'TTD',
        'PD',
        'OPD',
    ],

    'keep_title_with_dot' => [
        'Prov.',
        'Bid.',
        'Kec.',
        'Kel.',
        'Kab.',
    ],

    'keep_upper_with_dot' => [
        'KA.',
    ],

    'honorifics' => [
        'Dr.',
        'dr.',
        'Prof.',
        'Ir.',
        'H.',
        'Hj.',
        'K.H.',
        'Nyi.',
        'Ny.',
        'Tn.',
        'Nn.',
        'drg.',
        'Ns.',
        'Apt.',
        'R.',
        'R.A.',
        'R.M.',
        'S.H.',
        'S.E.',
        'S.Kom.',
        'S.Pd.',
        'S.Sos.',
        'S.T.',
        'S.Si.',
        'S.Farm.',
        'S.Psi.',
        'S.Ag.',
        'S.I.Kom.',
        'S.IP.',
        'S.Sn.',
        'S.Ked.',
        'S.Gz.',
        'S.Ars.',
        'S.P.',
        'M.M.',
        'M.Pd.',
        'M.Kom.',
        'M.Si.',
        'M.Kn.',
        'M.H.',
        'M.T.',
        'M.E.',
        'M.Sc.',
        'M.A.',
        'M.Ag.',
        'M.Farm.',
        'M.Psi.',
        'Sp.A.',
        'Sp.OG.',
        'Sp.PD.',
        'Sp.B.',
        'Sp.KK.',
    ],

    // Pilih 'dr' (dokter umum) atau 'doktor' (gelar akademik).
    'honorific_priority' => 'dr',

    'regex_upper_case' => [
        '/^M{0,3}(CM|CD|D?C{0,3})(XC|XL|L?X{0,3})(IX|IV|V?I{0,3})$/i',
        '/^(\d+\/)?\/?((S|D)[1-4])(\/(S|D)[1-4])*$/i',
    ],
];
